name: Build and test
description: "Build the project and run tests via CMake"

runs:
  using: "composite"
  steps:
    - name: Build
      run: cmake --build '${{github.workspace}}/build' --parallel "$(nproc)"
      shell: bash

    - name: Test
      working-directory: '${{github.workspace}}/build'
      run: |
        # https://github.com/actions/runner-images/issues/8399
        PATH="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH"
        ctest --output-on-failure -j"$(nproc)"
      shell: bash
