# vim: sw=2
name: lupdate

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntu-qt6:
    name: Qt 6.10.0 / Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup CMake
        uses: ./.github/actions/cmake
        with:
          qt_version: 6.10.0
          qt_arch: linux_gcc_64
          qt_target: desktop
          use_qt6: ON
          ccache: 'false'
          modules: qtserialport qtwebsockets

      - name: Refresh translation files
        run: cmake --build '${{github.workspace}}/build' --target update_translations

      - name: Check changes
        run: git diff --exit-code
